[package]
name = "muscp"
version = "2022.4.22"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glob = "0.3.0"
sanitize-filename = "0.3.0"
